### ISSUE TITLE
没有高亮，不能格式化？

### ISSUE THREAD

**Issue by ioolllzzzz** [Emeryao/we-app-vscode#1]
![image](https://user-images.githubusercontent.com/23166590/33465567-9199cc1a-d683-11e7-8d78-573659a33228.png)

**Comment by emeryao** [comment]
with the extension [Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) installed in your VS Code add a settings like this
```
    "beautify.language": {
        "html": [
            "wxml"
        ]
    }
```
